
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  main:
    allow-circular-references: true


  open-in-view: false
  jpa:

      hibernate:
        ddl-auto: update

      show-sql: false

server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: 1234567

